new architecture

diff --git a/sendreport b/sendreport
--- a/sendreport
+++ b/sendreport
@@ -20,7 +20,7 @@ if [[ -f "${CUSTOM_CONFIG_FILE_NAME}" ]]; then
 	source "${CUSTOM_CONFIG_FILE_NAME}"
 fi
 
-ssr::validate_configuration
+ssr::validate_configuration "EMAIL_RECIPIENT" "EMAIL_SENDER"
 
 # Get output type from script options, perform validation of script options
 output_type=$( ssr::get_output_type_from_script_options "$@" )
@@ -30,6 +30,7 @@ fi
 
 # Get the text of the report
 reports_content=""
+errors_content=""
 
 for i in "${!REPORTS[@]}"
 do
@@ -44,15 +45,24 @@ do
   fi
 
   # Function with the same name as report is called (+ "ssr::" prefix)
-  report_content=$( "ssr::${REPORTS[$i]}" )
+  report_content=$( "ssr::${REPORTS[$i]}" 2>&1 )
 
-  # In case the report ended with error exit status, show warning message
-  if [[ $? -gt 0 ]]; then
-    report_content=$( printf "${REPORT_ERROR_TEMPLATE}" "${REPORTS[$i]}" )
-  fi
-
-  reports_content="${reports_content}${report_content}"
+  case $? in
+    0 )
+      reports_content="${reports_content}${report_content}"
+      ;;
+    "${EXIT_CODE_CONFIG_ERROR}" )
+      errors_content+="Error in \"${REPORTS[$i]}\" report: ${report_content}"
+      ;;
+    * )
+      report_content=$( printf "${REPORT_ERROR_TEMPLATE}" "${REPORTS[$i]}" )
+      ;;
+  esac
 done
+
+if [[ ! -z "${errors_content}" ]]; then
+  ssr::throw_error 1 "${errors_content}"
+fi
 
 mail_headers=$( ssr::create_mail_headers )
 mail_html=$( printf "${MAIN_TEMPLATE}" "${EMAIL_SUBJECT}" "${reports_content}" )
